<!DOCTYPE html>
<html lang="en">
<head>
    <?php require 'partials/head.phtml'; ?>
    <title>Add Task</title>
</head>
<body>
<div class="container">
    <div class="card text-dark bg-light mb-3 border shadow-sm w-75 m-4">
        <div class="card-body">
            <h2 class="card-title">Add Task</h2>
            <form method="POST" action="/task">
                <div class="mb-3">
                    <label for="task" class="form-label">Task</label>
                    <input type="text" id="task" name="task"/>
                </div>
                <a href="./tasks" class="btn btn-primary">Cancel</a>
                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
</div>
</body>
</html>