<?php

use App\ViewHelpers\TasksViewHelper;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require 'partials/head.phtml'; ?>
    <title>View Tasks</title>
</head>
<body>
<div class="container">
    <div class="m-4">
        <h2>Todos</h2>
        <a href="./task" class="btn btn-primary mb-2">Add Task</a>
        <?php echo TasksViewHelper::displayTasks($tasks); ?>
    </div>
</div>
</body>
</html>